on:
  push:
    branches:
    - main
name: CI
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Get short SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ctm002/pilaresverdes-frontend:${{ github.sha }}
          build-args: |
            VITE_BUILD_HASH=${{ steps.vars.outputs.short_sha }}
      - name: Set permissions for private key
        run: |
            mkdir -p ~/.ssh/
            echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/key.pem
            chmod 400 ~/.ssh/key.pem
            cat >>~/.ssh/config <<END
            Host staging
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/key.pem
              StrictHostKeyChecking no
            END
        env:
            SSH_USER: ${{ vars.STAGING_SSH_USER }}
            SSH_HOST: ${{ vars.STAGING_SSH_HOST }}
      - name: Pull Docker image
        run: |
            ssh staging 'sudo docker pull ctm002/pilaresverdes-frontend:${{ github.sha }}'
      - name: Stop running container
        run: |
            ssh staging 'sudo docker stop webserver || true'
            ssh staging 'sudo docker rm webserver || true'
      - name: Run new container
        run: |
            ssh staging 'sudo docker run -d \
              --restart=unless-stopped \
              --name webserver \
              --network=red-local-docker \
              -v ~/nginx/nginx.conf:/etc/nginx/nginx.conf:ro \
              -v ~/nginx/conf.d/:/etc/nginx/conf.d/ \
              -p 80:80 ctm002/pilaresverdes-frontend:${{ github.sha }}'
